server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411       # zipkin 客户端的 地址  可是通过这个看见服务之间的调用关系
  sleuth:
    sampler:
      probability: 1




mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.echo.entity


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      defaultZone: http://localhost:7001/eureka
    instance:
      instance-id: payment8003
      prefer-ip-address: true





